import {test} from 'node:test';
import assert from 'node:assert/strict';
import {ExtractionMission,EXTRACTION_BOSS_TIME} from '../src/extraction.ts';
const advance=(m:ExtractionMission,s:number)=>{for(let i=0;i<Math.ceil(s/.025);i++)m.update(.025);};
const enemy=(m:ExtractionMission,x=480,y=300,hp=7)=>{const e={id:99,kind:'tank' as const,x,y,hp,maxHp:7,age:0,fireTimer:100,warning:0,aim:{x:480,y:450},anchor:x};m.foes.push(e);return e;};
test('four-direction flight normalizes diagonals, stays in bounds and caps large deltas',()=>{const m=new ExtractionMission();m.moveX=m.moveY=1;m.update(1);assert.ok(Math.abs(Math.hypot(m.helicopter.x-480,m.helicopter.y-450)-13)<.001);advance(m,4);assert.equal(m.helicopter.x,830);assert.equal(m.helicopter.y,510);m.moveX=m.moveY=-1;advance(m,8);assert.equal(m.helicopter.x,130);assert.equal(m.helicopter.y,240);});
test('twin cannons obey their fire rate and stop after the mission ends',()=>{const m=new ExtractionMission();m.fire();m.fire();assert.equal(m.shots.length,2);advance(m,.15);m.fire();assert.equal(m.shots.length,4);m.state='won';const t=m.time;m.fire();m.rocket();m.update(1);assert.equal(m.time,t);assert.equal(m.shots.length,4);});
test('rockets exhaust, recharge over eight seconds and blast nearby armor',()=>{const m=new ExtractionMission(()=>.5);m.rocket();advance(m,.5);m.rocket();advance(m,.5);m.rocket();advance(m,.5);assert.equal(m.rockets,0);const count=m.shots.length;m.rocket();assert.equal(m.shots.length,count);advance(m,6.6);assert.equal(m.rockets,1);m.foes=[];const a=enemy(m,480,330),b=enemy(m,540,330);m.rocket();advance(m,.3);assert.equal(a.hp,1);assert.equal(b.hp,1);});
test('fast player projectiles use swept hits and award a target kill only once',()=>{const m=new ExtractionMission();enemy(m,480,300,1);m.shots=[{x:480,y:340,vx:0,vy:-1500,side:'player',rocket:false,life:1,damage:1},{x:480,y:340,vx:0,vy:-1500,side:'player',rocket:false,life:1,damage:1}];m.update(.05);assert.equal(m.kills,1);assert.equal(m.score,150);assert.equal(m.foes.length,0);});
test('enemy fire damages the helicopter and overlapping hits get brief protection',()=>{const m=new ExtractionMission();for(let i=0;i<3;i++)m.shots.push({x:480,y:410,vx:0,vy:1200,side:'enemy',rocket:false,life:1,damage:6});m.update(.05);assert.equal(m.health,94);assert.ok(m.damageFlash>0);advance(m,.3);m.shots.push({x:480,y:410,vx:0,vy:1200,side:'enemy',rocket:false,life:1,damage:8});m.update(.05);assert.equal(m.health,86);});
test('repair and rocket pickups collect on contact and respect their caps',()=>{const m=new ExtractionMission();m.health=91;m.rockets=2;m.supplies=[{x:480,y:450,kind:'repair'},{x:480,y:450,kind:'rockets'}];m.update(.025);assert.equal(m.health,100);assert.equal(m.rockets,3);assert.equal(m.supplies.length,0);assert.equal(m.drainEvents().filter(e=>e.kind==='airsupply').length,2);});
test('enemy warning locks a position before the aimed burst',()=>{const m=new ExtractionMission(()=>.5);const e=enemy(m);e.fireTimer=0;m.update(.025);assert.ok(e.warning>0);const aim={...e.aim};m.moveX=1;advance(m,.9);assert.deepEqual(e.aim,aim);assert.ok(m.shots.some(s=>s.side==='enemy'));assert.ok(e.fireTimer>0);});
test('final gunship spawns once, needs destruction to win and loses to simultaneous lethal damage',()=>{const m=new ExtractionMission();m.time=EXTRACTION_BOSS_TIME;m.update(.025);const boss=m.foes.find(e=>e.kind==='gunship');assert.ok(boss);assert.equal(boss.hp,56);m.time=100;m.update(.025);assert.equal(m.state,'playing');boss.hp=1;m.shots=[{x:boss.x,y:boss.y+25,vx:0,vy:-1000,side:'player',rocket:false,life:1,damage:1}];m.update(.05);assert.equal(m.bossCleared,true);assert.equal(m.departing,true);assert.equal(m.state,'playing');advance(m,3);assert.equal(m.state,'won');const loss=new ExtractionMission();loss.bossCleared=true;loss.time=100;loss.health=6;loss.shots=[{x:480,y:410,vx:0,vy:1200,side:'enemy',rocket:false,life:1,damage:6}];loss.update(.05);assert.equal(loss.state,'lost');});
test('missing the gunship deadline loses and finished state freezes everything',()=>{const m=new ExtractionMission();m.time=130;m.update(.025);assert.equal(m.state,'lost');const t=m.time,p={...m.helicopter};m.moveX=1;m.update(1);assert.equal(m.time,t);assert.deepEqual(m.helicopter,p);});
test('a pilot anticipating incoming fire can clear the route and gunship at every difficulty',()=>{for(const difficulty of ['rookie','regular','veteran'] as const){let r=53;const m=new ExtractionMission(()=>{r=r*16807%2147483647;return r/2147483647;},difficulty);for(let i=0;i<5300&&m.state==='playing';i++){
const target=m.foes.filter(e=>e.y<m.helicopter.y-35&&e.hp>0).sort((a,b)=>(a.kind==='gunship'?-1000:0)-(b.kind==='gunship'?-1000:0)||b.y-a.y)[0];
if(i%4===0){let best=Infinity;for(const dx of [-1,0,1])for(const dy of [-1,0,1]){const norm=Math.max(1,Math.hypot(dx,dy));let cost=0;for(const t of [.1,.2,.3,.4,.5,.6]){const x=Math.max(130,Math.min(830,m.helicopter.x+dx/norm*260*t)),y=Math.max(240,Math.min(510,m.helicopter.y+dy/norm*260*t));cost+=(Math.abs(x-(target?.x??480))*.008+Math.abs(y-450)*.006);for(const s of m.shots)if(s.side==='enemy'&&s.life>t){const dist=Math.hypot(x-s.x-s.vx*t,y-s.y-s.vy*t);cost+=Math.max(0,55-dist)*3;}for(const e of m.foes){if(e.kind!=='aa'&&e.kind!=='radar'){const dist=Math.hypot(x-e.x,y-e.y-(e.kind==='gunship'?0:e.kind==='fighter'?92:57)*t);cost+=Math.max(0,65-dist)*3;}if(e.warning>0&&t>e.warning){const a=Math.atan2(e.aim.y-e.y-15,e.aim.x-e.x),speed=360*(difficulty==='rookie'?.8:difficulty==='veteran'?1.2:1),flight=t-e.warning;const dist=Math.hypot(x-e.x-Math.cos(a)*speed*flight,y-e.y-15-Math.sin(a)*speed*flight);cost+=Math.max(0,60-dist)*2;}}}cost+=Math.hypot(dx,dy)*.05;if(cost<best){best=cost;m.moveX=dx;m.moveY=dy;}}}
m.fire();if(target&&Math.abs(target.x-m.helicopter.x)<25&&target.hp>=5)m.rocket();m.update(.025);
}assert.equal(m.state,'won',difficulty);assert.ok(m.bossCleared);assert.ok(m.health>0);}});
test('wave mix stays bounded and the gunship is announced exactly once',()=>{const m=new ExtractionMission(()=>.5);const kinds=new Set<string>();let bosses=0;for(let i=0;i<3200&&m.state==='playing';i++){m.moveX=Math.sin(m.time);m.moveY=0;m.update(.025);m.health=100;for(const e of m.foes)kinds.add(e.kind);bosses+=m.drainEvents().filter(e=>e.kind==='airboss').length;assert.ok(m.foes.length<=13);}for(const kind of ['jeep','tank','boat','fighter','gunship','aa','radar'])assert.ok(kinds.has(kind),kind);assert.equal(bosses,1);});
const site=(m:ExtractionMission)=>{const aa={id:101,kind:'aa' as const,x:225,y:200,hp:12,maxHp:12,age:0,fireTimer:0,warning:0,aim:{x:480,y:450},anchor:225,site:7},radar={...aa,id:102,kind:'radar' as const,x:290,y:130,hp:8,maxHp:8,fireTimer:100,anchor:290};m.foes.push(aa,radar);return {aa,radar};};
test('ground sites arrive as linked armored pairs and stay fixed to scrolling terrain',()=>{const m=new ExtractionMission(()=>.5);advance(m,8.05);const aa=m.foes.find(e=>e.kind==='aa'),radar=m.foes.find(e=>e.kind==='radar');assert.ok(aa&&radar);assert.equal(aa.site,radar.site);assert.equal(aa.hp,12);assert.equal(radar.hp,8);const x=aa.x,y=aa.y;advance(m,.1);assert.equal(aa.x,x);assert.ok(Math.abs(aa.y-y-15.5)<.001);assert.equal(m.drainEvents().filter(e=>e.kind==='airinstallation').length,1);});
test('active radar leads movement and boosts AA missiles; destroying it weakens the next salvo',()=>{const m=new ExtractionMission(()=>.5);const {aa,radar}=site(m);m.moveX=1;m.update(.025);assert.ok(aa.aim.x>m.helicopter.x);m.moveX=0;advance(m,.55);const first=m.shots.filter(s=>s.missile);assert.equal(first.length,3);assert.ok(first.every(s=>Math.abs(Math.hypot(s.vx,s.vy)-360)<.01));assert.ok(aa.fireTimer<=.95);radar.hp=0;aa.fireTimer=0;aa.warning=0;m.shots=[];m.update(.025);assert.deepEqual(aa.aim,m.helicopter);advance(m,.55);const next=m.shots.filter(s=>s.missile);assert.equal(next.length,2);assert.ok(next.every(s=>Math.abs(Math.hypot(s.vx,s.vy)-300)<.01));assert.ok(aa.fireTimer>1.5);});
test('a rocket splashes both site structures and ground sites do not collide with the helicopter',()=>{const m=new ExtractionMission(()=>.5);const {aa,radar}=site(m);aa.fireTimer=100;m.shots=[{x:225,y:250,vx:0,vy:-1000,side:'player',rocket:true,damage:6,life:1}];m.update(.05);assert.equal(aa.hp,6);assert.equal(radar.hp,2);m.helicopter={x:aa.x,y:aa.y+155*.025};m.update(.025);assert.equal(m.health,100);assert.equal(aa.hp,6);});

test('an unattended helicopter takes early aimed hits and cannot coast through the opening',()=>{for(const difficulty of ['rookie','regular','veteran'] as const){for(let seed=1;seed<=8;seed++){let randomState=seed;const m=new ExtractionMission(()=>{randomState=randomState*16807%2147483647;return randomState/2147483647;},difficulty);advance(m,4);assert.ok(m.health<100,`${difficulty}: opening attack must hit`);advance(m,20);assert.equal(m.state,'lost',`${difficulty}: idle pilot must lose before 24 seconds`);}}});

test('holding fire without maneuvering cannot coast through the first fighter groups',()=>{for(const difficulty of ['rookie','regular','veteran'] as const){const m=new ExtractionMission(()=>.5,difficulty);for(let i=0;i<1400&&m.state==='playing';i++){m.fire();m.update(.025);}assert.equal(m.state,'lost',difficulty);assert.ok(m.kills>0);}});
test('completed Extraction flies up off screen before reporting victory and ignores combat input',()=>{const m=new ExtractionMission();m.bossCleared=true;m.time=100;m.update(.025);assert.equal(m.departing,true);const y=m.helicopter.y,hp=m.health;m.moveX=1;m.moveY=1;m.fire();m.rocket();assert.equal(m.shots.length,0);advance(m,.5);assert.equal(m.helicopter.x,480);assert.ok(m.helicopter.y<y);assert.equal(m.health,hp);assert.equal(m.state,'playing');advance(m,3);assert.equal(m.state,'won');assert.ok(m.helicopter.y<-80);assert.equal(m.drainEvents().filter(e=>e.kind==='victory').length,1);});
